- name: "compose : add systemd service for docker-compose"
  copy:
    src: docker-compose@.service
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: "compose : create Docker Compose directory"
  file:
    name: /etc/docker/compose
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: "compose : reload systemd daemon"
  systemd:
    daemon_reload: true
  become: true
