- name: "packages : remove old Docker versions"
  package:
    name:
    - docker
    - docker-engine
    - docker.io
    state: absent
  become: true

- name: "packages : add Docker's GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
  become: true

- name: "packages : add Docker stable repository"
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  become: true

- name: "packages : add Docker edge repository"
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} edge"
  become: true

- name: "packages : install packages"
  package:
    name:
    - docker-ce
    - docker-compose
    state: present
  become: true
